// 彩蛋 + 光标
(function(){var nameEl=document.getElementById('nameEgg');var tipEl=document.getElementById('loveTip');
if(nameEl&&tipEl){nameEl.addEventListener('mouseenter',function(){tipEl.classList.add('show')});nameEl.addEventListener('mouseleave',function(){tipEl.classList.remove('show')})}
var tg=document.getElementById('taglineEgg');var titles=['高司令指定扮演者','光影捕手 · 创造者','互联网游民','资深摸鱼艺术家','Late Night Code Warrior','白日梦摄影师傅','业余设计师','正在寻找人生的 Ctrl+Z'];
if(tg){tg.addEventListener('click',function(){var c=titles.shift();titles.push(c);this.textContent=c;this.classList.remove('clicked');void this.offsetHeight;this.classList.add('clicked')})}
var sp=document.querySelector('.splash-title');if(sp){sp.addEventListener('click',function(e){e.stopPropagation();var t=this.querySelector('.title-sweep')||this.querySelector('.title-base');if(t){var o=t.textContent;t.textContent='终于找到彩蛋了 🎉';setTimeout(function(){t.textContent=o},1800)}})}
var cx=document.getElementById('crossEgg');if(cx){cx.addEventListener('click',function(e){var p=document.createElement('div');p.style.cssText='position:fixed;pointer-events:none;z-index:99998;inset:0';var colors=['#F97316','#14B8A6','#EC4899','#FBBF24','#0EA5E9'];for(var i=0;i<20;i++){(function(){var d=document.createElement('div');var s=Math.random()*8+3;var ci=colors[Math.floor(Math.random()*colors.length)];var a=Math.random()*Math.PI*2;var dist=Math.random()*140+30;d.style.cssText='position:absolute;width:'+s+'px;height:'+s+'px;border-radius:50%;background:'+ci+';left:'+(e.clientX||window.innerWidth/2)+'px;top:'+(e.clientY||window.innerHeight/2)+'px;transform:translate(-50%,-50%);opacity:0;transition:all .7s cubic-bezier(0.22,1,0.36,1)';p.appendChild(d);requestAnimationFrame(function(){d.style.opacity='0.8';d.style.transform='translate(-50%,-50%) translate('+Math.cos(a)*dist+'px,'+Math.sin(a)*dist+'px) scale(0)'})})()}document.body.appendChild(p);setTimeout(function(){p.style.opacity='0';setTimeout(function(){p.remove()},800)},1200)})}
var ph=document.getElementById('photoHint');var phc=0;
if(ph){ph.addEventListener('click',function(){phc++;if(phc>=5){phc=0;var msgs=['"快门背后的世界，比看到的更美"','"每张照片都是一个故事"','"按下快门的瞬间，时间就停止了"','"最好的相机，是你带着的那台"'];var msg=msgs[Math.floor(Math.random()*msgs.length)];this.textContent='✨ '+msg;this.style.color='rgba(20,184,166,0.5)';this.style.fontSize='13px';setTimeout(function(){if(ph)ph.textContent='📷 点击 5 次→';ph.style.color='';ph.style.fontSize=''},2800)}})}
var ppdots=document.getElementById('photoPages');
if(ppdots){ppdots.addEventListener('click',function(e){if(e.target.classList.contains('photo-page-line')){var idx=Array.from(this.children).indexOf(e.target);var caps=['山间晨雾 — 阿尔山','钢筋之间 — 上海','窗里窗外 — 东京','落叶满径 — 京都','一瞬之光 — 云南','星河万里 — 川西','海天一色','城市脉搏','旧时光','新视界','在路上','归途'];var cap=caps[idx%caps.length];var pc=document.getElementById('photoCounter');if(pc){var old=pc.textContent;pc.textContent=cap;pc.style.color='rgba(20,184,166,0.4)';pc.style.fontSize='16px';setTimeout(function(){pc.textContent=old;pc.style.color='';pc.style.fontSize=''},1200)}}})}
var gst=document.querySelector('#games .section-title');
if(gst){gst.addEventListener('dblclick',function(){var msgs=[['🏆','成就「资深玩家」已解锁！'],['🎮','成就「游戏收藏家」已解锁！'],['💪','成就「时长 1000h+」已解锁！'],['🕹️','成就「全平台制霸」已解锁！'],['⚡','成就「电竞之心」已解锁！']];var m=msgs[Math.floor(Math.random()*msgs.length)];var t=document.createElement('div');t.className='egg-toast';t.innerHTML='<span class="egg-icon">'+m[0]+'</span>'+m[1];document.body.appendChild(t);requestAnimationFrame(function(){t.classList.add('show')});for(var i=0;i<16;i++){(function(){var cf=document.createElement('div');var s=Math.random()*6+4;var clrs=['#F97316','#14B8A6','#EC4899','#FBBF24','#0EA5E9'];cf.style.cssText='position:fixed;pointer-events:none;z-index:99996;width:'+s+'px;height:'+s+'px;background:'+clrs[Math.floor(Math.random()*clrs.length)]+';left:'+(window.innerWidth*0.5+(Math.random()-0.5)*200)+'px;top:'+(window.innerHeight*0.4-10)+'px;border-radius:2px;opacity:1;transition:all 1.2s cubic-bezier(0.22,1,0.36,1)';document.body.appendChild(cf);requestAnimationFrame(function(){cf.style.transform='translateY('+(Math.random()*120+40)+'px) rotate('+(Math.random()*360)+'deg)';cf.style.opacity='0'});setTimeout(function(){cf.remove()},1400)})()}setTimeout(function(){t.classList.remove('show');setTimeout(function(){t.remove()},600)},2800)})}
var gss=document.querySelector('#games .section-subtitle');if(gss)gss.title='🎮 双击标题有惊喜';
var mss=document.querySelector('#movies .section-subtitle');
if(mss){var mqs=['"电影是生活的渐近线" — 安德烈·巴赞','"我们都有美好的时光" — 肖申克的救赎','"carpe diem" — 死亡诗社','"人生就像一盒巧克力" — 阿甘正传'];var mi=0;mss.style.cursor='pointer';mss.addEventListener('click',function(){var q=mqs[mi%mqs.length];mi++;var old=this.textContent;this.textContent=q;this.style.color='rgba(236,72,153,0.6)';setTimeout(function(){mss.textContent=old;mss.style.color=''},2500)});mss.title='点击切换电影金句'}
var CU=document.getElementById('cursor-ring'),CD=document.getElementById('cursor-dot');
var _ct=0;document.addEventListener('mousemove',function(e){if(!CD||!CU)return;CD.style.left=e.clientX+'px';CD.style.top=e.clientY+'px';requestAnimationFrame(function(){CU.style.left=e.clientX+'px';CU.style.top=e.clientY+'px'});var n=Date.now();if(n-_ct<40)return;_ct=n;for(var pi=0;pi<2;pi++){(function(){var c=document.createElement('div');c.className='cr-particle';var s=Math.random()*4+2;var clrs=['rgba(20,184,166,0.6)','rgba(14,165,233,0.45)','rgba(236,72,153,0.35)','rgba(251,191,36,0.3)'];c.style.cssText='position:fixed;border-radius:50%;pointer-events:none;z-index:99998;mix-blend-mode:difference;width:'+s+'px;height:'+s+'px;background:'+clrs[Math.floor(Math.random()*clrs.length)]+';left:'+(e.clientX+(Math.random()-0.5)*6)+'px;top:'+(e.clientY+(Math.random()-0.5)*6)+'px;transform:translate(-50%,-50%) scale(1);opacity:0.8';document.body.appendChild(c);requestAnimationFrame(function(){c.style.transition='all .6s cubic-bezier(0.22,1,0.36,1)';c.style.opacity='0';c.style.transform='translate(-50%,-50%) translate('+(Math.random()-0.5)*40+'px,'+(Math.random()-0.5)*40+'px) scale(0)';setTimeout(function(){if(c.parentNode)c.remove()},700)})})()}});
document.querySelectorAll('a,button,input,img,.site-link,.meme-row-inner img,.name-img,.hero-btn,.photo-card,.game-grid-item,.movie-card').forEach(function(e){e.addEventListener('mouseenter',function(){if(CU)CU.classList.add('hover');if(CD)CD.classList.add('hover')});e.addEventListener('mouseleave',function(){if(CU)CU.classList.remove('hover');if(CD)CD.classList.remove('hover')})});
document.addEventListener('mousedown',function(){if(CU)CU.classList.add('click')});document.addEventListener('mouseup',function(){if(CU)CU.classList.remove('click')});
document.addEventListener('mouseleave',function(){if(CU)CU.style.display='none';if(CD)CD.style.display='none'});document.addEventListener('mouseenter',function(){if(CU)CU.style.display='';if(CD)CD.style.display=''});})();
