// 摄影画廊
(function(){var pf=["DSC09198-1.JPG","DSC01708-1.JPG","1780071501759.jpg","mmexport1768918568845.jpg","流星1.jpg","流星2.jpg","20240407-DSC00401.jpg","20240407-DSC00459.jpg","20240409-DSC00535.jpg","20240409-DSC00606.jpg","20240409-DSC00631.jpg","20240905-2024-08-20 101206.jpg","DSC01622.jpg","DSC01648-1.jpg","DSC01649.jpg","DSC01900-1.jpg","微信图片_20240727174633-1.jpg","微信图片_20240727174638-1.jpg","未命名 (1 - 16).jpg","未命名 (2 - 16).jpg"];var sk=document.getElementById('photoStack'),pp=document.getElementById('photoPages'),pc=document.getElementById('photoCounter'),pb=document.getElementById('photoPrev'),pn=document.getElementById('photoNext');var cp=0,anim=0,items=[];
pf.forEach(function(f,i){var el=document.createElement('div');el.className='photo-card';var im=document.createElement('img');im.alt='';im.decoding='async';el.appendChild(im);var lb=document.createElement('div');lb.className='pc-label';var sn=document.createElement('span');sn.textContent='IMG_'+(i+1<10?'0':'')+(i+1)+' — '+f;lb.appendChild(sn);el.appendChild(lb);el.addEventListener('click',function(){var Z=document.getElementById('zoomLightbox'),ZI=Z.querySelector('img');ZI.src=im.src;Z.classList.add('open');document.body.style.overflow='hidden';var MN=document.getElementById('main');MN.style.overflowY='hidden'});sk.appendChild(el);items.push(el)});
function ld(i){var idx=((i%pf.length)+pf.length)%pf.length;var im=items[idx].querySelector('img');if(!im.src)im.src='pic/照片展示/'+encodeURI(pf[idx])}
function sz(){var vw=window.innerWidth,vh=window.innerHeight;var maxW=Math.min(vw*0.5,560);var maxH=vh*0.65;items.forEach(function(el){el.style.width=maxW+'px';el.style.height=maxH+'px'});return{maxW:maxW,maxH:maxH}}
function go(i){if(anim)return;if(i===cp)return;anim=1;ld(i);ld(i+1);ld(i-1);var dir=i>cp||(cp===0&&i===items.length-1)?1:-1;cp=i;ren(true);setTimeout(function(){anim=0;ud()},600);ud()}
function ren(animate){var s=sz();var gap=Math.max(s.maxW*0.15,30);var offL=-s.maxW*0.5-gap;var offR=s.maxW*0.5+gap;var offF=-s.maxW*1.2;var n=items.length;items.forEach(function(el,i){var d=i-cp;if(d>n/2)d-=n;if(d<-n/2)d+=n;if(animate)el.style.transition='all .6s cubic-bezier(0.34,1.56,0.64,1)';else el.style.transition='none';if(d===0){el.className='photo-card focus';el.style.transform='translateX(0)'}else if(d===-1){el.className='photo-card side';el.style.transform='translateX('+offL+'px)'}else if(d===1){el.className='photo-card side';el.style.transform='translateX('+offR+'px)'}else{el.className='photo-card far';el.style.transform='translateX('+(d<0?offF:-offF)+'px)'}})}
function ud(){pp.innerHTML='';for(var i=0;i<pf.length;i++){(function(idx){var d=document.createElement('button');d.className='photo-page-line'+(idx===cp?' active':'');d.addEventListener('click',function(){go(idx)});pp.appendChild(d)})(i)}if(pc)pc.textContent=String(cp+1).padStart(2,'0')+' / '+String(pf.length).padStart(2,'0')}
pb.addEventListener('click',function(){go((cp-1+pf.length)%pf.length);rt()});pn.addEventListener('click',function(){go((cp+1)%pf.length);rt()});
sz();ud();ld(0);ld(1);ld(pf.length-1);ren(false);
var pa;function rt(){if(pa)clearInterval(pa);pa=setInterval(function(){if(!anim)go((cp+1)%pf.length)},5000)}
sk.addEventListener('mouseenter',function(){if(pa)clearInterval(pa)});sk.addEventListener('mouseleave',function(){rt()});
var po=new IntersectionObserver(function(e){e.forEach(function(en){if(en.isIntersecting){rt();var ps=document.querySelector('.photo-stage');if(ps&&!ps._parallax){ps._parallax=true;ps.addEventListener('mousemove',function(ev){var fc=ps.querySelector('.photo-card.focus');if(!fc)return;var r=fc.getBoundingClientRect();var cx=r.left+r.width/2,cy=r.top+r.height/2;var dx=(ev.clientX-cx)/r.width,dy=(ev.clientY-cy)/r.height;var mx=dx*4,my=dy*4;fc.style.transform='translateX(0) rotateX('+(-my)+'deg) rotateY('+mx+'deg)'});ps.addEventListener('mouseleave',function(){var fc=ps.querySelector('.photo-card.focus');if(fc)fc.style.transform='translateX(0) rotateX(0deg) rotateY(0deg)'})}}else if(pa)clearInterval(pa)})},{threshold:0.1});po.observe(document.getElementById('photos'));
window.addEventListener('resize',function(){ren(false)});rt()})();
